### ISSUE TITLE
Enhancement: Add fs/findFiles VFS request

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/langserver#4]
Per discussion with @sqs it would be nice to add one more operation to `fs` layer - `fs/findFiles` (name may change) which will perform advanced search for files eliminating the need to invoke multiple `fs/readDir` requests. 

Return value should be array of strings where items denote POSIX-like file paths relative to specified root directory. Example 'foo/bar/baz.go', '.gitignore'

Request parameters should be the following
- root (string, '/') - optional search root. If not specified, defaults to '/'
- extensions (string[], null) - if specified, only files with the names ending with any of extensions given will be included. Example ['.js', '.jsx', '.ts', '.tsx']
- recursive (boolean, true) - indicates that search should be recursive
- excludeDotfiles (boolean, true) - excludes files and directories starting with dot (`.git`)
- files(string[], null) - if specified, only existing files from a given set will be included. Files may be absolute and relative (to root) path-like elements
- include(string[], null) - glob-like patterns (applied to files and directories). Pattern without POSIX path separators and glob symbols tested against file or directory's base name, others tested against relative (to root) path
- exclude(string[], null) - glob-like patterns (applied to files and directories). Pattern without POSIX path separators and glob symbols tested against file or directory's base name, others tested against relative (to root) path. If current item is a directory and matches exclude rule, no search will be performed in the given directory sub-folders (case: `node_modules`)

WDYT?

**Comment by sqs** [comment]
@alexsaveliev @renfredxh I updated the spec per the discussion. See https://github.com/sourcegraph/language-server-protocol/pull/3. Let's move this discussion there.
